-- Usuaris
CREATE TABLE USERS
(
	USERNAME VARCHAR(50) NOT NULL PRIMARY KEY
	,PASSWORD VARCHAR(500) NOT NULL
	,ENABLED BOOLEAN NOT NULL
);
CREATE TABLE AUTHORITIES
(
	USERNAME VARCHAR(50) NOT NULL
	,AUTHORITY VARCHAR(50) NOT NULL
	,CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);
CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTHORITIES (USERNAME,AUTHORITY);
-- Cocktails
CREATE TABLE COCKTAILS
(
	ID_DRINK INTEGER NOT NULL PRIMARY KEY
	,NAME NVARCHAR(200) NOT NULL
	,THUMB VARCHAR(500) NOT NULL
	,INGREDIENTS NVARCHAR(1000) NOT NULL
	,INSTRUCTIONS NVARCHAR(1000) NOT NULL
);
CREATE INDEX IX_NAME ON COCKTAILS (NAME);